const defaults={scrollDown:'j',scrollUp:'k',top:'g g',bottom:'G',back:'Ctrl+H',forward:'Ctrl+L',nextWindow:'Alt+J',previousWindow:'Alt+K',openSettings:'s'};
chrome.runtime.onInstalled.addListener(()=>chrome.storage.sync.set(defaults)); chrome.commands.onCommand.addListener(c=>{if(c==='open-settings')chrome.runtime.openOptionsPage()});
const updateUrl='https://github.com/csaben/vim-chromium';
async function checkUpdate(){try{const r=await fetch('https://raw.githubusercontent.com/csaben/vim-chromium/main/manifest.json',{cache:'no-store'}),m=await r.json(),newer=m.version!==chrome.runtime.getManifest().version;await chrome.storage.local.set({updateAvailable:newer,latestVersion:m.version,updateUrl});chrome.action.setBadgeText({text:newer?'UPD':''});chrome.action.setBadgeBackgroundColor({color:'#d93025'})}catch(_){}}
chrome.runtime.onInstalled.addListener(()=>{chrome.alarms.create('update-check',{periodInMinutes:60});checkUpdate()});chrome.runtime.onStartup.addListener(checkUpdate);chrome.alarms.onAlarm.addListener(a=>{if(a.name==='update-check')checkUpdate()});checkUpdate();
async function moveWindow(d){const c=await chrome.windows.getCurrent(),w=(await chrome.windows.getAll({windowTypes:['normal']})).filter(x=>x.id!==c.id).sort((a,b)=>a.id-b.id);if(!w.length)return;const i=w.findIndex(x=>x.id>c.id),t=d==='next'?w[i<0?0:i]:w[i<0?w.length-1:Math.max(0,i-1)];await chrome.windows.update(t.id,{focused:true})}
const attached=new Set();
async function setDocsMode(tabId,enabled){const target={tabId};if(enabled&&!attached.has(tabId)){await chrome.debugger.attach(target,'1.3');attached.add(tabId)}else if(!enabled&&attached.has(tabId)){await chrome.debugger.detach(target);attached.delete(tabId)}}
async function sendDocsKey(tabId,m){await setDocsMode(tabId,true);const codes={ArrowLeft:37,ArrowUp:38,ArrowRight:39,ArrowDown:40,Home:36,End:35},vk=codes[m.key],modifiers=(m.altKey?1:0)|(m.ctrlKey?2:0)|(m.shiftKey?8:0),target={tabId},base={key:m.key,code:m.key,windowsVirtualKeyCode:vk,nativeVirtualKeyCode:vk,modifiers};await chrome.debugger.sendCommand(target,'Input.dispatchKeyEvent',{type:'rawKeyDown',...base});await chrome.debugger.sendCommand(target,'Input.dispatchKeyEvent',{type:'keyUp',...base})}
chrome.debugger.onDetach.addListener(source=>{if(source.tabId)attached.delete(source.tabId)});
chrome.runtime.onMessage.addListener((m,s,send)=>{if(m.action==='window'){moveWindow(m.direction).then(()=>send({ok:true}));return true}if(m.action==='settings'){chrome.runtime.openOptionsPage();return}if(m.action==='docs-mode'&&s.tab?.id){setDocsMode(s.tab.id,m.enabled).then(()=>send({ok:true})).catch(e=>send({ok:false,error:e.message}));return true}if(m.action==='docs-key'&&s.tab?.id){sendDocsKey(s.tab.id,m).then(()=>send({ok:true})).catch(e=>send({ok:false,error:e.message}));return true}});
