const defaults={scrollDown:'j',scrollUp:'k',top:'g g',bottom:'G',back:'Ctrl+H',forward:'Ctrl+L',nextWindow:'Alt+J',previousWindow:'Alt+K',openSettings:'s'};
let keys={...defaults},pending=false,timer,docsNormal=false;
chrome.storage.sync.get(defaults,v=>keys={...defaults,...v});chrome.storage.onChanged.addListener(c=>Object.keys(c).forEach(k=>keys[k]=c[k].newValue));
let topHost='';try{topHost=window.top.location.hostname}catch(_){}
const docsAncestor=[...location.ancestorOrigins].some(origin=>{try{return new URL(origin).hostname==='docs.google.com'}catch(_){return false}});
const inDocs=location.hostname==='docs.google.com'||location.hostname.endsWith('.googleusercontent.com')||topHost==='docs.google.com'||docsAncestor;
const key=e=>{const plain=e.key.length===1?e.key.toLowerCase():e.key;const implicit=e.shiftKey&&e.key.length===1&&e.key===e.key.toUpperCase();return `${e.ctrlKey?'Ctrl+':''}${e.altKey?'Alt+':''}${e.shiftKey&&!implicit?'Shift+':''}${e.metaKey?'Meta+':''}${implicit?e.key:plain}`};
const typing=e=>e.isContentEditable||['INPUT','TEXTAREA','SELECT'].includes(e.tagName),stop=e=>{e.preventDefault();e.stopPropagation()};
const docsDocument=()=>{try{return window.top.document}catch(_){return document}};
const viewport=()=>{if(!inDocs)return document.scrollingElement;const doc=docsDocument();const candidates=[...doc.querySelectorAll('.kix-appview-editor,.kix-appview-editor-container,[role="document"]')];return candidates.find(v=>v.scrollHeight>v.clientHeight)||doc.scrollingElement};
const docsScroll=(kind,amount=0)=>{if(window===window.top||docsDocument()!==document){const v=viewport();if(kind==='move')v.scrollBy({top:amount,behavior:'smooth'});else v.scrollTo({top:kind==='top'?0:v.scrollHeight,behavior:'smooth'});return}window.top.postMessage({type:'vim-chromium-docs-scroll',kind,amount},'*')};
if(window===window.top&&location.hostname==='docs.google.com')window.addEventListener('message',e=>{if(e.source===window||!e.data||e.data.type!=='vim-chromium-docs-scroll')return;const v=viewport();if(e.data.kind==='move')v.scrollBy({top:e.data.amount,behavior:'smooth'});else v.scrollTo({top:e.data.kind==='top'?0:v.scrollHeight,behavior:'smooth'})});
const move=(amount)=>{if(inDocs)docsScroll('move',amount);else viewport().scrollBy({top:amount,behavior:'smooth'})};
const scrollDown=()=>move(Math.max(120,innerHeight*.4)),scrollUp=()=>move(-Math.max(120,innerHeight*.4));
const docsMove=(source,keyName,mods={})=>{stop(source);chrome.runtime.sendMessage({action:'docs-key',key:keyName,ctrlKey:!!mods.ctrlKey,shiftKey:!!mods.shiftKey,altKey:!!mods.altKey})};
function docsKey(e,k){if(!docsNormal){if(e.key==='Escape'||e.code==='CapsLock'){docsNormal=true;stop(e);chrome.runtime.sendMessage({action:'docs-mode',enabled:true});return 'handled'}return 'blocked'}if(e.key==='i'||e.key==='a'||e.key==='o'){docsNormal=false;pending=false;stop(e);chrome.runtime.sendMessage({action:'docs-mode',enabled:false});return 'handled'}if(e.key==='Escape'||e.code==='CapsLock'){stop(e);return 'handled'}if(pending){clearTimeout(timer);pending=false;if(`g ${k}`===keys.top){docsMove(e,'Home',{ctrlKey:true});return 'handled'}}if(k==='g'&&keys.top==='g g'){pending=true;timer=setTimeout(()=>pending=false,800);stop(e);return 'handled'}const motions={h:['ArrowLeft',{}],j:['ArrowDown',{}],k:['ArrowUp',{}],l:['ArrowRight',{}],w:['ArrowRight',{ctrlKey:true}],e:['ArrowRight',{ctrlKey:true}],b:['ArrowLeft',{ctrlKey:true}],'0':['Home',{}],'$':['End',{}],G:['End',{ctrlKey:true}]};if(motions[k]){docsMove(e,...motions[k]);return 'handled'}if(e.key.length===1){stop(e);return 'handled'}return 'command'}
document.addEventListener('keydown',e=>{if(!e.isTrusted)return;const k=key(e);if(inDocs){const result=docsKey(e,k);if(result!=='command')return}if(!inDocs&&typing(e.target))return;const v=viewport();const a={scrollDown,scrollUp,top:()=>v.scrollTo({top:0,behavior:'smooth'}),bottom:()=>v.scrollTo({top:v.scrollHeight,behavior:'smooth'}),back:()=>history.back(),forward:()=>history.forward(),nextWindow:()=>chrome.runtime.sendMessage({action:'window',direction:'next'}),previousWindow:()=>chrome.runtime.sendMessage({action:'window',direction:'previous'}),openSettings:()=>chrome.runtime.sendMessage({action:'settings'})};for(const[n,f]of Object.entries(a))if(k===keys[n]){stop(e);f();return}},true);
